version: '0.1'

services:
  pgdatabase:
    container_name: pgdatabase_container
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=amazon_scrape
    volumes:
      - './db/data:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - './db/pgadmin:/var/lib/pgadmin'
    ports:
      - "8080:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge